### ISSUE TITLE
[Tracking] Abstractions and core libraries tooling - TypeScript

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-typescript#41]
In order for us to move with confidence to GA, we need better tooling for
  the abstraction and core libraries. This includes:

 - [x] unit tests for the libraries
 - [x] eslint configuration for linting
 - [x] cobertura reports generation via https://github.com/microsoft/kiota-typescript/pull/1457
 - [x] udpate the readmes to remove the tasks via https://github.com/microsoft/kiota-typescript/pull/1457
[AB#11101](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/11101)
 - [x] doc comment for all the things that are not already commented in the  abstraction libs (constructors, static things, not implementing/inheriting...) via https://github.com/microsoft/kiota-typescript/pull/1457
 - [ ] browserlist configuration for compat

**Comment by sebastienlevert** [comment]
@baywet is this still relevant?

**Comment by baywet** [comment]
yep, I've been keeping the checklist up to date.
