### ISSUE TITLE
[Tracking] Add executions tests for validating all the core libraries

### ISSUE THREAD

**Issue by nikithauc** [microsoft/kiota-typescript#50]
- [ ] Add unit tests which are real time for each library.
- [ ] Add a sample request builder repo, link with the other packages in this repo and add real time unit tests using request builders.
- [ ] Updates pipelines to validate PRs and publish process with the real time tests
