### ISSUE TITLE
[ Tracking] Set up tests infrastructure

### ISSUE THREAD

**Issue by nikithauc** [microsoft/kiota-typescript#65]
- [ ] Add node and browser tests to abstractions
- [ ] Add node and browser tests to fetch
- [ ] Add node and browser tests to serialization json
- [ ] Add node and browser tests to serialization text
- [ ] Add node and browser tests to authorization azure
- [ ] Add integrated run time tests
